= Deploying Clusters using Hosted Control Planes

== Introduction

Using hosted control planes is a way to deploy the Control Plane of Red Hat OpenShift Container Platform clusters as pods on other clusters dramatically decreasing the time it takes to provision a new cluster. Worker nodes are still deployed as virtual machines and managed using the new `Machine.cluster.x-k8s.io/v1beta1` API.

The instructions in this workshop cover the following scenarios:

* Introduction (this document)
* https://github.com/marrober/acm-workshop/blob/main/documentation/modules/ROOT/pages/007_explore_environment.adoc[Exploring the Environment]
* https://github.com/marrober/acm-workshop/blob/main/documentation/modules/ROOT/pages/008_deploy_cluster.adoc[Deploy a cluster using HyperShift]

== Documentation

Further documentation about enabling, configuring and using hosted control planes can be found at the following link:

* Openshift 4.18 documentation for https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html/hosted_control_planes/index[hosted control planes]

== Information you will need

Once your environment has been provisioned the following information will be available in the service page of your Environment on the Red Hat Demo System. You will also receive an e-mail with the following information:

|===
|Console URL|https://console-openshift-console.apps.cluster-p6mj8.sandbox2651.opentlc.com
|Cluster admin user|admin
|Cluster admin password|EDdYfrIoygYEPP4n
|Cluster users|user1 .. user2
|Cluster user (common) password|3pNVc0JCPRZeby4i
|SSH command to connect to the bastion VM|ssh lab-user@bastion.p6mj8.sandbox2651.opentlc.com
|SSH password|YhTVpCoq1P8j
|Service Management URL|https://demo.redhat.com/services/user-wkulhane-redhat-com/sandboxes-gpte.ocp4-acm-hypershift.prod
|===

Make note of the following information:

* The SSH command to connect to you environment's bastion's VM
* The password to be used with user `lab-user` on the bastion VM
* Also the OpenShift console URL along with the credentials for the `admin` user.

