apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: limit-range-policy
  labels:
    app: layers-app
    policy: limit-range
  annotations:
    apps.open-cluster-management.io/github-path: acm/policies/limit-range
    apps.open-cluster-management.io/github-branch: main
spec:
  channel: layers/layers-app-latest
  placement:
    placementRef:
      kind: PlacementRule
      name: dev-clusters
