apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- web-terminal-policy.yaml
- web-terminal-placement-binding.yaml
- placement-rule.yaml
patches:
- patch: |-
    - op: add
      path: /metadata/namespace
      value: rhacm-policies
  target:
    labelSelector: "policy=web-terminal"
