apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: web-terminal
  labels:
    policy: web-terminal
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: web-terminal
        spec:
          severity: medium
          remediationAction: enforce
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: web-terminal
                  namespace: openshift-operators
                spec:
                  channel: fast
                  installPlanApproval: Automatic
                  name: web-terminal
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace